# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-14 11:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=30)),
                ('passwd', models.CharField(max_length=30)),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='pic',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photo.User'),
        ),
    ]
