# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-09 03:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0002_friend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='user1',
        ),
        migrations.RemoveField(
            model_name='friend',
            name='user2',
        ),
        migrations.AddField(
            model_name='user',
            name='firends',
            field=models.ManyToManyField(related_name='_user_firends_+', to='photo.User'),
        ),
        migrations.DeleteModel(
            name='Friend',
        ),
    ]
