# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-09 04:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0003_auto_20161209_0338'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=300, null=True)),
                ('pic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photo.Pic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photo.User')),
            ],
        ),
    ]
