# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-09 09:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
